apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opc.fullname" . }}-common
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "opc.labels" . | nindent 4 }}
data:
  # 共享环境变量（明文，非敏感）
  TZ: "Asia/Shanghai"
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai"
  SPRING_JACKSON_TIME_ZONE: "Asia/Shanghai"
  LOGGING_LEVEL_COM_RUOYI: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
