{{- if .Values.serviceMonitor.enabled }}
{{- $promLabels := .Values.serviceMonitor.labels }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "opc.fullname" . }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "opc.labels" . | nindent 4 }}
    {{- with $promLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: opc-platform
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/actuator/prometheus" }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: true
{{- end }}
