server:
  port: 9322

spring:
  application:
    name: opc-hr
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aiopc-mysql:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Opc@2026!

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ruoyi.opc.hr.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    com.ruoyi.opc.hr: debug
